get-object:
   path: /get-object
   controller: App\Controller\ObjectController::get
add-object:
   path: /add-object
   controller: App\Controller\ObjectController::add
update-object:
   path: /update-object
   controller: App\Controller\ObjectController::update
delete-object:
   path: /delete-object
   controller: App\Controller\ObjectController::delete
get-taxi:
   path: /get-taxi
   controller: App\Controller\TaxiController::get
add-taxi:
   path: /add-taxi
   controller: App\Controller\TaxiController::add
